// Generated by CoffeeScript 1.9.2
(function() {
  var Config, ajax, events, utils;

  events = require('./events');

  utils = require('./utils');

  ajax = require('./ajax');

  Config = (function() {
    Config.debug = true;

    Config.EVENT_READY = 'config:ready.slsapi';

    Config.EVENT_FAIL = 'config:fail.slsapi';

    function Config(opcoes) {
      var self, xhr;
      this.id = utils.md5(JSON.stringify(opcoes)) + parseInt(1000 * Math.random());
      this.children = [];
      self = this;
      this.parseOpcoes(opcoes);
      if (opcoes.urlConfServico) {
        xhr = ajax.get(opcoes.urlConfServico);
        xhr.done(function(res) {
          self.parseOpcoes(res.body);
          return events.trigger(self.id, Config.EVENT_READY);
        });
        xhr.fail(function(err) {
          return events.trigger(self.id, Config.EVENT_FAIL, {
            err: err,
            message: 'Error: não foi possível carregar configuração da visualização'
          });
        });
      } else {
        setTimeout((function() {
          return events.trigger(self.id, Config.EVENT_READY);
        }), 5);
      }
    }

    Config.prototype.parseOpcoes = function(opcoes, view) {
      this.opcoes = new utils.Dicionario(opcoes);
      this.serverURL = this.opcoes.get('serverURL', this.serverURL || 'http://sl.wancharle.com.br');
      this.createURL = this.opcoes.get('createURL', this.createURL || (this.serverURL + "/note/create/"));
      this.loginURL = this.opcoes.get('loginURL', this.loginURL || (this.serverURL + "/user/login/"));
      this.logoutURL = this.opcoes.get('logoutURL', this.logoutURL || (this.serverURL + "/user/logout/"));
      this.notesURL = this.opcoes.get('notesURL', this.notesURL || (this.serverURL + "/note/"));
      this.notebookURL = this.opcoes.get('notebookURL', this.notebookURL || (this.serverURL + "/notebook/"));
      if (!view) {
        this.coletorNotebookId = this.opcoes.get('storageNotebook', '');
      }
      return this.noteid = this.opcoes.get('noteid', this.noteid || '');
    };

    Config.prototype.register = function(container, configInstance) {
      if (configInstance.parseOpcoes) {
        configInstance.parseOpcoes(this.opcoes);
      }
      return this.children.push([container, configInstance]);
    };

    Config.prototype.toJSON = function() {
      var child, configInstance, container, i, json, len, ref;
      json = {
        'storageNotebook': this.coletorNotebookId,
        'noteid': this.noteid
      };
      ref = this.children;
      for (i = 0, len = ref.length; i < len; i++) {
        child = ref[i];
        container = child[0], configInstance = child[1];
        json[container] = configInstance.toJSON();
      }
      return JSON.parse(JSON.stringify(json));
    };

    return Config;

  })();

  module.exports = {
    'Config': Config
  };

}).call(this);
