// Generated by CoffeeScript 1.9.2
(function() {
  var CLIENT_SIDE, DataSource, DataSourceGoogle, TABLETOP,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  if (typeof process.browser === 'undefined') {
    CLIENT_SIDE = false;
    TABLETOP = require('tabletop');
  } else {
    TABLETOP = Tabletop;
    CLIENT_SIDE = true;
  }

  DataSource = require('./datasource').DataSource;

  DataSourceGoogle = (function(superClass) {
    extend(DataSourceGoogle, superClass);

    function DataSourceGoogle() {
      return DataSourceGoogle.__super__.constructor.apply(this, arguments);
    }

    DataSourceGoogle.prototype.loadData = function(config) {
      return TABLETOP.init({
        'key': this.url,
        'callback': (function(_this) {
          return function(data, tabletop) {
            return _this.onDataLoaded(data, _this, config);
          };
        })(this),
        'simpleSheet': true
      });
    };

    return DataSourceGoogle;

  })(DataSource);

  module.exports = {
    DataSourceGoogle: DataSourceGoogle
  };

}).call(this);
