// Generated by CoffeeScript 1.9.2
(function() {
  var DataSource, ajax, contexto, events, utils,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  events = require('./events');

  ajax = require('./ajax');

  utils = require('./utils');

  contexto = {};

  contexto = utils;

  DataSource = (function() {
    DataSource.EVENT_LOADED = 'datasourceLoaded.slsapi';

    DataSource.EVENT_LOAD_FAIL = 'datasourceLoadFail.slsapi';

    DataSource.EVENT_REQUEST_FAIL = 'datasourceRequestFail.slsapi';

    function DataSource(url, func_code) {
      this.addItem = bind(this.addItem, this);
      this._getCatOrCreate = bind(this._getCatOrCreate, this);
      var e;
      this.valid = true;
      if (url && typeof func_code === 'function') {
        this.url = url;
        this.func_code = func_code;
      } else {
        if (typeof func_code === 'string') {
          try {
            this.func_code = utils.string2function(func_code);
            this.url = url;
          } catch (_error) {
            e = _error;
            console.error(e, 'Error ao tentar criar funcao de conversao apartir de texto');
            this.valid = false;
          }
        } else {
          console.error("Error de configuração de fonte:", {
            url: url,
            func_code: func_code
          });
          this.valid = false;
        }
      }
      this.notes = [];
      this.notesChildren = {};
      this.categories = {};
      this.categories_id = {};
    }

    DataSource.prototype.isValid = function() {
      return this.valid;
    };

    DataSource.prototype._getCatOrCreate = function(i) {
      var cat;
      cat = this.categories[i.cat];
      if (cat) {
        return cat;
      } else {
        this.categories[i.cat] = [];
        this.categories_id[i.cat] = i.cat_id;
        return this.categories[i.cat];
      }
    };

    DataSource.prototype.addItem = function(i, func_convert) {
      var cat, e, geoItem;
      try {
        geoItem = func_convert(i, contexto);
      } catch (_error) {
        e = _error;
        console.error("Erro em DataSource::addItem: " + e.message, i);
        geoItem = null;
      }
      if (geoItem) {
        if (!geoItem.id) {
          geoItem.hashid = "" + (parseFloat(geoItem.latitude).toFixed(7)) + (parseFloat(geoItem.longitude).toFixed(7)) + (utils.md5(JSON.stringify(geoItem)));
        } else {
          if (!geoItem.hashid) {
            geoItem.hashid = geoItem.id;
          }
          geoItem.id = void 0;
        }
        this.notes.push(geoItem);
        if (geoItem.id_parent) {
          this.addChild(geoItem.id_parent, geoItem);
        }
        cat = this._getCatOrCreate(geoItem);
        cat.push(geoItem);
      }
      return geoItem;
    };

    DataSource.prototype.addChild = function(parentId, child) {
      if (!this.notesChildren[parentId]) {
        this.notesChildren[parentId] = [];
      }
      return this.notesChildren[parentId].push(child);
    };

    DataSource.prototype.loadData = function(config, force) {
      var xhr;
      if (force == null) {
        force = false;
      }
      if (config.usarCache && config.noteid) {
        this.loadFromCache(config);
        return;
      }
      xhr = ajax.get(this.url, {
        type: 'json'
      });
      xhr.done((function(_this) {
        return function(res) {
          var json;
          json = res.body;
          if (res.type.toLowerCase().indexOf("text") > -1) {
            json = JSON.parse(res.text);
          }
          return _this.onDataLoaded(json, _this, config);
        };
      })(this));
      return xhr.fail((function(_this) {
        return function(err) {
          console.log('error');
          return events.trigger(config.id, DataSource.EVENT_REQUEST_FAIL, err);
        };
      })(this));
    };

    DataSource.prototype.onDataLoaded = function(data, fonte, config) {
      var d, e, i, j, len;
      try {
        for (i = j = 0, len = data.length; j < len; i = ++j) {
          d = data[i];
          this.addItem(d, fonte.func_code);
        }
        return events.trigger(config.id, DataSource.EVENT_LOADED);
      } catch (_error) {
        e = _error;
        console.error(e.toString());
        events.trigger(config.id, DataSource.EVENT_LOAD_FAIL);
      }
    };

    DataSource.prototype.loadFromCache = function(config) {
      return ajax.getJSON(config.urlsls + "/note/listaExternal?noteid=" + config.noteid + "&fonteIndex=" + i, (function(_this) {
        return function(data) {
          var fonte2;
          fonte2 = {
            url: _this.url,
            func_code: function(i) {
              return i;
            }
          };
          return _this.onDataLoaded(data, fonte2);
        };
      })(this));
    };

    return DataSource;

  })();

  module.exports = {
    DataSource: DataSource
  };

}).call(this);
