// Generated by CoffeeScript 1.10.0
(function() {
  var DataSource, DataSourceGoogle, TABLETOP, isRunningOnBrowser,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  isRunningOnBrowser = require('./utils').isRunningOnBrowser;

  if (!isRunningOnBrowser) {
    TABLETOP = require('tabletop');
  } else {
    TABLETOP = Tabletop;
  }

  DataSource = require('./datasource').DataSource;

  DataSourceGoogle = (function(superClass) {
    extend(DataSourceGoogle, superClass);

    function DataSourceGoogle() {
      return DataSourceGoogle.__super__.constructor.apply(this, arguments);
    }

    DataSourceGoogle.prototype.loadData = function(config) {
      return TABLETOP.init({
        'key': this.url,
        'callback': (function(_this) {
          return function(data, tabletop) {
            return _this.onDataLoaded(data, _this, config);
          };
        })(this),
        'simpleSheet': true
      });
    };

    return DataSourceGoogle;

  })(DataSource);

  module.exports = {
    DataSourceGoogle: DataSourceGoogle
  };

}).call(this);
