// Generated by CoffeeScript 1.9.2
(function() {
  var CLIENT_SIDE, bind, emitter, events, trigger;

  emitter = null;

  if (typeof process.browser === 'undefined') {
    CLIENT_SIDE = false;
    events = require('events');
    emitter = new events.EventEmitter();
  } else {
    CLIENT_SIDE = true;
  }

  trigger = function(event, param) {
    if (CLIENT_SIDE) {
      return $(document).trigger(event, param);
    } else {
      return emitter.emit(event, param);
    }
  };

  bind = function(event, cb) {
    if (CLIENT_SIDE) {
      return $(document).on(event, function(caller, params) {
        return cb(params);
      });
    } else {
      return emitter.on(event, cb);
    }
  };

  module.exports = {
    trigger: trigger,
    on: bind
  };

}).call(this);
