// Generated by CoffeeScript 1.9.2
(function() {
  var Notes, ajax;

  ajax = require('./ajax');

  Notes = (function() {
    Notes.instances = {};

    Notes.getInstance = function(config) {
      return this.instances[config.id];
    };

    function Notes(config) {
      Notes.instances[config.id] = this;
      this.config = config;
    }

    Notes.prototype.getByUser = function(user_id, callback, callback_fail) {
      var xhr;
      xhr = ajax.get(this.config.notesURL + "?user=" + user_id);
      xhr.done(function(data) {
        return callback(data);
      });
      return xhr.fail(function() {
        return callback_fail();
      });
    };

    Notes.prototype.getByQuery = function(query, callback, callback_fail) {
      var xhr;
      xhr = ajax.get(this.config.notesURL + "?" + query);
      xhr.done(function(data) {
        return callback(data);
      });
      return xhr.fail(function() {
        return callback_fail();
      });
    };

    Notes.prototype.update = function(note_id, queryparams, callback, callback_fail) {
      var xhr;
      xhr = ajax.post(this.config.notesURL + "update/" + note_id + "/", queryparams);
      xhr.done(function(data) {
        return callback(data);
      });
      return xhr.fail(function() {
        return callback_fail();
      });
    };

    Notes.prototype["delete"] = function(note_id, callback) {
      var xhr;
      xhr = ajax.del({
        url: "" + this.config.notesURL + note_id
      });
      return xhr.done(function(data) {
        return callback(data);
      });
    };

    Notes.prototype.enviar = function(note, notebookId, callback_ok, callback_fail) {
      var ft, options, params;
      if (notebookId == null) {
        notebookId = null;
      }
      if (callback_ok == null) {
        callback_ok = (function() {});
      }
      if (callback_fail == null) {
        callback_fail = (function() {});
      }
      if (!notebookId) {
        if (!this.config.coletorNotebookId) {
          console.error('NotebookId não foi informado!');
          return;
        } else {
          notebookId = this.config.coletorNotebookId;
        }
      }
      params = note;
      params.notebook = notebookId;
      $(document).trigger('slsapi.note:uploadStart');
      if (note.fotoURI) {
        options = new FileUploadOptions();
        options.params = params;
        options.fileKey = "foto";
        options.fileName = note.fotoURI.substr(note.fotoURI.lastIndexOf('/') + 1);
        options.mimeType = "image/jpeg";
        options.params.fotoURL = true;
        ft = new FileTransfer();
        return ft.upload(note.fotoURI, encodeURI(this.config.createURL), (function(_this) {
          return function(r) {
            $(document).trigger('slsapi.note:uploadFinish');
            return callback_ok(r);
          };
        })(this), (function(_this) {
          return function(error) {
            $(document).trigger('slsapi.note:uploadFail');
            return callback_fail(error);
          };
        })(this), options);
      } else {
        return $.post(this.config.createURL, params, function(json) {
          $(document).trigger('slsapi.note:uploadFinish');
          return callback_ok(json);
        }, 'json').fail(function(error) {
          $(document).trigger('slsapi.note:uploadFail');
          return callback_fail(error);
        });
      }
    };

    return Notes;

  })();

  module.exports = {
    'Notes': Notes
  };

}).call(this);
