// Generated by CoffeeScript 1.9.2
(function() {
  var Notebook, ajax;

  ajax = require('./ajax');

  Notebook = (function() {
    Notebook.instances = {};

    Notebook.getInstance = function(config) {
      return this.instances[config.id];
    };

    function Notebook(config) {
      Notebook.instances[config.id] = this;
      this.config = config;
    }

    Notebook.prototype.getByName = function(notebookName, callback, callbackFail) {
      var url, xhr;
      if (callbackFail == null) {
        callbackFail = null;
      }
      url = this.config.notebookURL + "?name=" + notebookName;
      xhr = ajax.get(url);
      xhr.done(function(res) {
        return callback(res.body);
      });
      return xhr.fail(function(err) {
        return callbackFail(err);
      });
    };

    Notebook.prototype.getById = function(notebookId, callback, callbackFail) {
      var url, xhr;
      if (callbackFail == null) {
        callbackFail = null;
      }
      url = this.config.notebookURL + "?id=" + notebookId;
      xhr = ajax.get(url);
      xhr.done(function(res) {
        return callback(res.body);
      });
      return xhr.fail(function(err) {
        return callbackFail(err);
      });
    };

    return Notebook;

  })();

  module.exports = {
    'Notebook': Notebook
  };

}).call(this);
