// Generated by CoffeeScript 1.10.0
(function() {
  var Config, DataSource, Mashup, Notebook, SLSAPI, User, ajax, dataPool, events, isRunningOnBrowser, notes, utils;

  isRunningOnBrowser = require('./utils').isRunningOnBrowser;

  utils = require('./utils');

  events = require('./events');

  ajax = require('./ajax');

  notes = require('./notes');

  Notebook = require('./notebook').Notebook;

  User = require('./user').User;

  Config = require('./config').Config;

  Mashup = require('./mashup').Mashup;

  dataPool = require('./datapool');

  DataSource = require('./datasource').DataSource;

  SLSAPI = (function() {
    function SLSAPI(opts) {
      this.config = new Config(opts);
      this.user = new User(this.config);
      this.notes = new notes.Notes(this.config);
      this.notebook = new Notebook(this.config);
      this.mashup = new Mashup(this.config);
    }

    SLSAPI.prototype.trigger = function(event, params) {
      return events.trigger(this.config.id, event, params);
    };

    SLSAPI.prototype.on = function(event, params) {
      return events.on(this.config.id, event, params);
    };

    SLSAPI.prototype.off = function(event, params) {
      return events.off(this.config.id, event, params);
    };

    return SLSAPI;

  })();

  SLSAPI.Config = Config;

  SLSAPI.Notes = notes.Notes;

  SLSAPI.User = User;

  SLSAPI.dataPool = dataPool;

  SLSAPI.DataSource = DataSource;

  SLSAPI.ajax = ajax;

  SLSAPI.utils = utils;

  SLSAPI.events = events;

  if (isRunningOnBrowser) {
    window.SLSAPI = SLSAPI;
  }

  module.exports = SLSAPI;

}).call(this);
